name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. Set up environment variables from GitHub Secrets
      - name: Set up environment variables
        run: |
          echo "${{ secrets.REACT_ENV }}" >> $GITHUB_ENV

      # 5. Build Docker image for React client
      - name: Build Docker image for React client
        run: |
          docker build -t hd3ce/cookeat-client:latest .

      # 6. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push hd3ce/cookeat-client:latest

      # 8. Invoke Lambda function to deploy on EC2
      - name: Invoke Lambda for deployment
        run: |
          curl -X POST https://mpila4kyx5.execute-api.ap-northeast-2.amazonaws.com/2024-09-11/cookeat-deploy-client \
          -H "x-api-key: ${{ secrets.X_API_KEY_CLIENT }}" \
          -H "Content-Type: application/json" \
          -d '{}'
